import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Forkast — Decode any menu",
  description: "AI-powered menu decoder. Know exactly what to order, what to skip, and why.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[#fafaf8]">
        <header className="sticky top-0 z-50 bg-white/90 backdrop-blur border-b border-gray-100">
          <div className="w-full px-6 h-14 flex items-center">
            <Link href="/" className="text-2xl font-extrabold text-gray-900 tracking-tight">
              fork<span className="text-orange-500">ast</span>
            </Link>
          </div>
        </header>
        <main className="max-w-lg mx-auto px-4 py-8">
          {children}
        </main>
        <footer className="max-w-lg mx-auto px-4 py-8 text-center text-xs text-gray-600 space-y-2">
          <p>
            <span className="font-bold text-gray-900">Forkast</span> aggregates publicly available content from restaurant websites, Yelp, TripAdvisor,
            Swiggy, The Infatuation, DoorDash, food blogs, social websites, and other sources across the web.
            Results are generated by AI based on what people have written online; they may be incomplete,
            outdated, or incorrect. This is not a substitute for your own judgment. What works for most
            reviewers may not work for you.
          </p>
          <p><span className="font-bold text-gray-900">Forkast</span> · AI-powered menu intelligence</p>
        </footer>
      </body>
    </html>
  );
}
